version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@ideal-postcodes/api-fixtures"
    versions:
    - 1.3.0
  - dependency-name: typedoc
    versions:
    - 0.20.18
    - 0.20.23
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.35
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 14.14.35
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: nock
    versions:
    - 13.0.9
  - dependency-name: semantic-release
    versions:
    - 17.4.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
  registries:
  - npm-registry-registry-npmjs-org
