version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: auto
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-type: "minor"
      production-dependencies:
        dependency-type: "production"
        update-type: "minor"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
